accountmanager-project/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    #TODO: listview
    path('account_list', views.AccountListView.as_view(), name='account_list'),
    #detail view
    path('account_detail/<int:pk>', views.AccountDetailView.as_view(), name='account_detail'),
    #CRUD - create
    path('account_create', views.AccountCreateView.as_view(), name='account_create'),
    #CRUD - uptade
    path('account_update/<int:pk>', views.AccountUpdateView.as_view(), name='account_update'),
    #CRUD - delete
    path('account_delete/<int:pk>', views.AccountDeleteView.as_view(), name='account_delete'),
]

accountmanager-project/accountmanager/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views as main_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', main_views.home, name='home'),
    path('accounts/signup/', main_views.signup, name="signup"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('', include('expenses.urls')),
]

accountmanager-project/main/models.py
from django.db import models

# Create your models here.

accountmanager-project/main/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model, login, logout, authenticate
# Create your views here.
def home(request):
    return render(request, 'main/home.html')

def signup(request):
    if request.method == 'GET':
        return render(request, 'registration/signup.html',
                      {'form': UserCreationForm()})
    else:
        form= UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password')
            authenticate(username=username, password=raw_password)
            user = get_user_model().objects.get(username=username)
            login(request, user)
            return render(request, 'main/home.html')
        else:
            error = form.errors

accountmanager-project/main/templates/main/base.html
<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://kit.fontawesome.com/ce727736ea.js" crossorigin="anonymous"></script>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.rtl.min.css" integrity="sha384-dpuaG1suU0eT09tx5plTaGMLBsfDLzUCCUXOY2j/LSvXYuG6Bqs43ALlhIqAJVRb" crossorigin="anonymous">

    <title>Main</title>
  </head>
  <body>
    <div class='container'>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Account Manager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href={% url 'home' %}>Home</a>
                  </li>
                  
                  <li class="nav-item">
                    <a class="nav-link" href={% url 'account:account_list' %}>My List</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="#">Action</a></li>
                      <li><a class="dropdown-item" href="#">Another action</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                  </li>
                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  {% if user.is_authenticated %}
                  <div class="container-fluid">
                    <span class="navbar-text">
                      Logged In {{ user.username }}
                    </span>
                  </div>
                  
                  
                  
                  <form action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button type="submit">logout</button>
                  </form>
                  {% else %}
                  Logged Out <a href={% url 'login' %}> Login </a> or <a href={% url 'signup' %}> Signup </a>
                  {% endif %}
                </ui>
              </div>
            </div>
          </nav>

        

        {% block content %}

        {% endblock %}
        </div>
        <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

        <!-- Option 2: Separate Popper and Bootstrap JS -->
        <!--
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
        -->
  </body>
</html>

accountmanager-project/main/templates/main/home.html
{% extends "main/base.html" %}

{% block content %}

<p>Home content</p>

{% endblock  %}